import Head from "next/head";
import { Inter } from "next/font/google";
import Nav from "@/src/Component/Navcomponent";
import React, { useEffect, useState } from "react";
import Header from "@/src/Component/Headercomponent";
import TransactionDisplay from "@/src/Content/TransactionDisplaycomponent";
import { EmptyState } from "@/src/Component/EmptyStatecomponent";
import { useQuery } from "react-query";
import { fetcher } from "@/src/api/helpers.tscomponent";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [filter, setFilter] = useState([{ naem: "" }]);
  const { data: user } = useQuery({
    queryFn: fetcher("user", "get"),
    queryKey: "user",
  });

  const { data: transactions } = useQuery({
    queryFn: fetcher("transactions", "get"),
    queryKey: "transactions",
  });

  const { data: wallet } = useQuery({
    queryFn: fetcher("wallet", "get"),
    queryKey: "wallet",
  });

  return (
    <>
      <Head>
        <title>Main Stack Test</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        style={{
          padding: "16px",
        }}
      >
        <Nav user={user} />
        <Header wallet={wallet} transactions={transactions} />
        {filter.length !== 0 ? (
          <TransactionDisplay transactions={transactions} />
        ) : (
          <EmptyState />
        )}
      </main>
    </>
  );
}
